#!/bin/sh

export DISPLAY=:0

BIN=/usr/bin/startfluxbox
PIDFILE=/var/run/fluxbox.pid

start() {
	printf "Starting Fluxbox: "
	start-stop-daemon -S -q -b -m -p $PIDFILE --exec $BIN --
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping Fluxbox: "
	start-stop-daemon -K -q -p $PIDFILE
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
	stop
	sleep 2
	start
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart|reload)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
